name: Hello world

on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello world step
        run: echo "Hellss"
        shell: bash
  updatebranhces:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.USER_TOKEN }}"
