name: Hello world

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello world step
        run: echo "Hellss"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: goodbye world step
        run: echo "goodbye swsww ${{ secrets.USER_TOKEN }}"
        shell: bash
