name: Pull request update

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-lastest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Update ALL THE PRS! 🎉
        run: echo "Hellss"
        shell: bash
        # uses: https://github.com/castastrophe/actions-pr-auto-update
        # with:
        #   token: ${{ secrets.USER_TOKEN }}
        #   include_drafts: true
